# Generated by Django 4.0.4 on 2022-05-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_item_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='available_stock',
        ),
        migrations.AddField(
            model_name='item',
            name='initial_stock',
            field=models.IntegerField(default=100),
        ),
    ]
